In [3]:
# =========多输出分类================
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
import numpy as np
X, y1 = make_classification(n_samples=10, n_features=100, n_informative=30, n_classes=3, random_state=1) # 生成分类数据集，10个样本，100个特征，30个有效特征，3种分类
y2 = shuffle(y1, random_state=1)  # 分类结果随机排序
y3 = shuffle(y1, random_state=2)  # 分类结果随机排序
Y = np.vstack((y1, y2, y3)).T  # 多种分类结果组合成
#print(X,y1,y2,y3)
print(X.shape)
print('多输出多分类器真实输出分类:\n',Y)
n_samples, n_features = X.shape # 10,100
n_outputs = Y.shape[1] # 3个输出
n_classes = 3 # 每种输出有3种分类
forest = RandomForestClassifier(n_estimators=100, random_state=1)  # 生成随机森林多分类器
multi_target_forest = MultiOutputClassifier(forest)  # 构建多输出多分类器
y_pred = multi_target_forest.fit(X, Y).predict(X)
print('多输出多分类器预测输出分类:\n',y_pred)

(10, 100)
多输出多分类器真实输出分类:
 [[2 2 0]
 [1 2 1]
 [2 1 0]
 [0 0 2]
 [0 2 1]
 [0 0 2]
 [1 1 0]
 [1 1 1]
 [0 0 2]
 [2 0 0]]
多输出多分类器预测输出分类:
 [[2 2 0]
 [1 2 1]
 [2 1 0]
 [0 0 2]
 [0 2 1]
 [0 0 2]
 [1 1 0]
 [1 1 1]
 [0 0 2]
 [2 0 0]]
